### ISSUE TITLE
Add this package to the list of GAP packages on GitHub

### ISSUE THREAD

**Issue by olexandr-konovalov** [chpech/COCO2P#1]
It was good to discover this repository. We maintain a list of all GAP packages with public source code repositories at https://gap-packages.github.io/ - would you be happy for me to add your package to the list?

**Comment by chpech** [comment]
Yes, by all means I would be happy if coco2p is added there.

--

**Comment by olexandr-konovalov** [comment]
Thanks - done in https://github.com/gap-packages/gap-packages.github.io/commit/3f427158ec5a84ea1fb37414d130b2ab567acb22. We also have some standard setups for GAP packages which may help package authors to maintain them - you may expect some more suggestions in the future!
